version: 2

models:
  - name: fact_listing_month
    description: "Monthly listing fact at listing_id, year_month."
    columns:
      - name: listing_id
        tests: [not_null]
      - name: year_month
        tests: [not_null]
      - name: host_month_id
        tests:
          - relationships:
              argument:
                to: ref('dim_host_month')
                field: host_month_id
      - name: property_month_id
        tests:
          - relationships:
              argument:
                to: ref('dim_property_month')
                field: property_month_id
      - name: suburb_key
        tests:
          - relationships:
              argument:
                to: ref('dim_suburb')
                field: suburb_key
      - name: is_active
        tests:
          - accepted_values:
              values: [0, 1]
      - name: number_of_stays
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
      - name: estimated_revenue_active
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns: [listing_id, year_month]


  - name: dim_property_month
    description: "Monthly property dimension."
    columns:
      - name: property_month_id
        tests: [not_null]
      - name: year_month
        tests: [not_null]
      - name: property_type
        tests: [not_null]
      - name: room_type
        tests: [not_null]
      - name: accommodates
        tests:
          - dbt_utils.expression_is_true:
              arguments:
                expression: ">= 1"


  - name: dim_suburb
    description: "Suburb LGA mapping."
    columns:
      - name: suburb_key
        tests: [unique, not_null]
      - name: suburb_name
        tests: [not_null]

  - name: dim_host_month
    description: "Monthly host dimension."
    columns:
      - name: host_month_id
        tests: [not_null]
      - name: host_id
        tests: [not_null]
      - name: year_month
        tests: [not_null]